services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-net
    labels:
      - traefik.enable=false

  app:
    build: .
    command: sh /app/entrypoint.sh
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - app-net
      - proxy
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.blueharvest.tls=true
      - traefik.http.routers.blueharvest.tls.certresolver=letsencrypt
      - traefik.http.routers.blueharvest.entrypoints=https
      - traefik.http.routers.blueharvest.rule=Host(`${DOMAIN}`)
      # Services
      - traefik.http.services.blueharvest.loadbalancer.server.port=80

networks:
  app-net:
    name: app-net
    external: false
  proxy:
    external: true